pipeline:
  test-redux:
    when:
      event: push
    image: node:10.16-alpine
    group: build
    commands:
      - apk add --no-cache --update git rsync
      - rm -rf /var/cache/apk/*
      - npm install hygen -g
      - mkdir redux
      - rsync -av . redux --exclude redux/ --exclude apollo/ --exclude .git/ --exclude node_modules/ && cd redux
      - npx hygen base new --app=test --team=test
      - npm i
      - npm run build
      - npm prune --production

  test-apollo:
    when:
      event: push
    image: node:10.16-alpine
    group: build
    commands:
      - apk add --no-cache --update git rsync
      - rm -rf /var/cache/apk/*
      - npm install hygen -g
      - mkdir apollo
      - rsync -av . apollo --exclude redux/ --exclude apollo/ --exclude .git/ --exclude node_modules/ && cd apollo
      - npx hygen base new --app=test --team=test --template=apollo
      - npm i
      - npm run build
      - npm prune --production