pipeline:
  build:
    when:
      event: push
    image: node:10.16-alpine
    commands:
      - apk add --no-cache --update git
      - rm -rf /var/cache/apk/*
      - npm ci
      - npm run build
      - npm prune --production
    environment:
      - RAZZLE_RELEASE=my-app-${DRONE_COMMIT_SHA:0:8}
      - PUBLIC_PATH=https://assets0.uswitch.com/s3/uswitch-assets-eu/my-app/

  assets:
    when:
      event: push
    image: python:3.6.2-alpine
    secrets: [ AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID ]
    commands:
      - apk add --no-cache make && rm -rf /var/cache/apk/*
      - pip install --upgrade awscli
      - aws s3 cp --region eu-west-1 --recursive build/public/ s3://uswitch-assets-eu/my-app/ --cache-control "max-age=31536000, immutable" --acl=public-read

  docker:
    when:
      event: push
    image: plugins/docker
    repo: registry.usw.co/uswitch/my-app
    dockerfile: Dockerfile
    build_args:
      - WORKDIR=/opt/my-app
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"

  deploy-staging:
    when:
      event: deployment
      environment: staging
  sentry-sourcemaps:
    when:
      event: push
      branch: master
    image: getsentry/sentry-cli:1.35
    secrets: [ SENTRY_AUTH_TOKEN ]
    commands:
      - sentry-cli releases -o uswitchcom -p my-app new my-app-${DRONE_COMMIT_SHA:0:8}
      - sentry-cli releases -o uswitchcom -p my-app files my-app-${DRONE_COMMIT_SHA:0:8} upload-sourcemaps build --rewrite --url-prefix /opt/my-app/build

    image: registry.usw.co/drone/deployment:latest
    tag_prefix: ${DRONE_DEPLOY_TO}
    secrets: [ KUBE_CA, KUBE_TOKEN, KUBE_SERVER ]
    kubernetes:
      template: [__kube__/hpa.yaml, __kube__/service.yaml, __kube__/deployment.yaml]
      namespace: my-team
    environment:
      replicas: "2"

  deploy-production:
    when:
      event: deployment
      environment: production
    image: registry.usw.co/drone/deployment:latest
    tag_prefix: ${DRONE_DEPLOY_TO}
    secrets: [ KUBE_CA, KUBE_TOKEN, KUBE_SERVER ]
    kubernetes:
      template: [__kube__/hpa.yaml, __kube__/service.yaml, __kube__/deployment.yaml]
      namespace: my-team
    environment:
      replicas: "4"

  notify-sentry-deployment:
    when:
      event: deployment
    image: getsentry/sentry-cli:1.35
    secrets: [ SENTRY_AUTH_TOKEN ]
    commands:
      - sentry-cli releases -o uswitchcom -p my-app finalize my-app-${DRONE_COMMIT_SHA:0:8}
      - sentry-cli releases -o uswitchcom -p my-app deploys my-app-${DRONE_COMMIT_SHA:0:8} new -e ${DRONE_DEPLOY_TO}
