---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app
  namespace: my-team
spec:
  maxReplicas: 20
  minReplicas: {{ .Env.replicas }}
  metrics:
    - type: Pods
      pods:
        metricName: koa_requests_per_second
        targetAverageValue: 5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-app-{{ .Env.DRONE_DEPLOY_TO }}
